In [3]:
import pandas as pd
import numpy as np
data = pd.read_csv(r"C:\Users\User\Desktop\Africa Conflicts.csv", sep=";")
df = pd.DataFrame(data)
df.head(10)

,ISO,EVENT_ID_CNTY,EVENT_ID_NO_CNTY,EVENT_DATE,YEAR,TIME_PRECISION,EVENT_TYPE,SUB_EVENT_TYPE,ACTOR1,ASSOC_ACTOR_1,...,ADMIN3,LOCATION,LATITUDE,LONGITUDE,GEO_PRECISION,SOURCE,SOURCE_SCALE,NOTES,FATALITIES,TIMESTAMP
0,12,ALG1,1,01-janvier-1997,1997,1,Violence against civilians,Attack,GIA: Armed Islamic Group,NaN,...,NaN,Douaouda,36672,2789,1,Algeria Watch,Other,5 January: Beheading of 5 citizens in Douaouda...,5,1582579226
1,12,ALG2,2,02-janvier-1997,1997,1,Violence against civilians,Attack,GIA: Armed Islamic Group,NaN,...,NaN,Hassasna,36133,883,1,Algeria Watch,Other,Two citizens were beheaded in Hassasna.,2,1582579226
2,12,ALG3,3,03-janvier-1997,1997,1,Violence against civilians,Attack,GIA: Armed Islamic Group,NaN,...,NaN,Hassi El Abed,34966,"-0,29",1,Algeria Watch,Other,Two citizens were killed in a raid on the vill...,2,1582579226
3,12,ALG4,4,04-janvier-1997,1997,1,Violence against civilians,Attack,GIA: Armed Islamic Group,NaN,...,NaN,Blida,36469,2829,1,Algeria Watch,Other,4 January: 16 citizens were murdered in the vi...,16,1582579226
4,12,ALG5,5,05-janvier-1997,1997,1,Violence against civilians,Attack,GIA: Armed Islamic Group,NaN,...,NaN,Douaouda,36672,2789,1,Algeria Watch,Other,5 January: Killing of 18 citizens in the Olivi...,18,1582579226
5,12,ALG6,6,06-janvier-1997,1997,1,Battles,Armed clash,Police Forces of Algeria (1994-1999),NaN,...,NaN,Ain Benian,36803,2922,1,Algeria Watch,Other,4 armed men were killed by security forces in ...,4,1582579226
6,12,ALG7,7,06-janvier-1997,1997,1,Violence against civilians,Attack,GIA: Armed Islamic Group,NaN,...,NaN,Hadjout,36514,2418,1,Algeria Watch,Other,6 January: 23 citizens were horribly mutilated...,23,1600121120
7,12,ALG8,8,07-janvier-1997,1997,1,Explosions/Remote violence,Remote explosive/landmine/IED,GIA: Armed Islamic Group,NaN,...,NaN,Ain Fakroun,35971,6874,1,Algeria Watch,Other,Explosion of a bomb in Ain Fakroun (Oum Bouagh...,7,1582579226
8,12,ALG11,11,07-janvier-1997,1997,1,Violence against civilians,Attack,GIA: Armed Islamic Group,NaN,...,NaN,Jijel,"36,8",5767,1,Algeria Watch,Other,The president of the chamber of bailiffs of th...,1,1582579226
9,12,ALG9,9,07-janvier-1997,1997,1,Explosions/Remote violence,Remote explosive/landmine/IED,GIA: Armed Islamic Group,NaN,...,NaN,Algiers,36752,3042,1,Algeria Watch,Other,7 January: Explosion of a bomb in the Didouche...,20,1582579226

In [4]:
df.shape

(65535, 29)

In [5]:
df.info

<bound method DataFrame.info of        ISO EVENT_ID_CNTY  EVENT_ID_NO_CNTY        EVENT_DATE  YEAR  \
0       12          ALG1                 1   01-janvier-1997  1997
1       12          ALG2                 2   02-janvier-1997  1997
2       12          ALG3                 3   03-janvier-1997  1997
3       12          ALG4                 4   04-janvier-1997  1997
4       12          ALG5                 5   05-janvier-1997  1997
...    ...           ...               ...               ...   ...
65530  404        KEN318               318   25-octobre-1998  1998
65531  404        KEN319               319  02-novembre-1998  1998
65532  404        KEN320               320  10-novembre-1998  1998
65533  404        KEN323               323  14-novembre-1998  1998
65534  404        KEN322               322  14-novembre-1998  1998

       TIME_PRECISION                  EVENT_TYPE    SUB_EVENT_TYPE  \
0                   1  Violence against civilians            Attack
1                   1  Violence against civilians            Attack
2                   1  Violence against civilians            Attack
3                   1  Violence against civilians            Attack
4                   1  Violence against civilians            Attack
...               ...                         ...               ...
65530               1  Violence against civilians            Attack
65531               1                    Protests  Peaceful protest
65532               1                     Battles       Armed clash
65533               1                     Battles       Armed clash
65534               1                     Battles       Armed clash

                                                ACTOR1  \
0                             GIA: Armed Islamic Group
1                             GIA: Armed Islamic Group
2                             GIA: Armed Islamic Group
3                             GIA: Armed Islamic Group
4                             GIA: Armed Islamic Group
...                                                ...
65530                      OLF: Oromo Liberation Front
65531                               Protesters (Kenya)
65532  SPLM/A: Sudan People's Liberation Movement/Army
65533  SPLM/A: Sudan People's Liberation Movement/Army
65534  SPLM/A: Sudan People's Liberation Movement/Army

                       ASSOC_ACTOR_1  ...           ADMIN3       LOCATION  \
0                                NaN  ...              NaN       Douaouda
1                                NaN  ...              NaN       Hassasna
2                                NaN  ...              NaN  Hassi El Abed
3                                NaN  ...              NaN          Blida
4                                NaN  ...              NaN       Douaouda
...                              ...  ...              ...            ...
65530  Borana Ethnic Militia (Kenya)  ...         Township           Tuli
65531               Students (Kenya)  ...  Nairobi Central        Nairobi
65532                            NaN  ...  Nairobi Central        Nairobi
65533                            NaN  ...  Nairobi Central        Nairobi
65534                            NaN  ...  Nairobi Central        Nairobi

      LATITUDE  LONGITUDE  GEO_PRECISION         SOURCE SOURCE_SCALE  \
0        36672       2789              1  Algeria Watch        Other
1        36133        883              1  Algeria Watch        Other
2        34966      -0,29              1  Algeria Watch        Other
3        36469       2829              1  Algeria Watch        Other
4        36672       2789              1  Algeria Watch        Other
...        ...        ...            ...            ...          ...
65530     1643      40343              1     All Africa     Regional
65531    -1283      36817              1     All Africa     Regional
65532    -1283      36817              1     All Africa     Regional
65533    -1283      36817              1     All Africa     Regional
65534    -1283      36817              1     All Africa     Regional

                                                   NOTES FATALITIES  \
0      5 January: Beheading of 5 citizens in Douaouda...          5
1                Two citizens were beheaded in Hassasna.          2
2      Two citizens were killed in a raid on the vill...          2
3      4 January: 16 citizens were murdered in the vi...         16
4      5 January: Killing of 18 citizens in the Olivi...         18
...                                                  ...        ...
65530  OLF and Borana ethnic militia attack civilians...         28
65531  University students protest over killing in Wa...          0
65532  Garangs SPLA security men raid home of Kerubin...          0
65533       Rival SPLA factions battle at police station          0
65534  Gang of youth loyal to Kerubinos SPLA faction ...          0

        TIMESTAMP
0      1582579226
1      1582579226
2      1582579226
3      1582579226
4      1582579226
...           ...
65530  1553544833
65531  1567465412
65532  1604344065
65533  1583194169
65534  1583194169

[65535 rows x 29 columns]>

In [6]:
df.isnull().sum()

ISO                     0
EVENT_ID_CNTY           0
EVENT_ID_NO_CNTY        0
EVENT_DATE              0
YEAR                    0
TIME_PRECISION          0
EVENT_TYPE              0
SUB_EVENT_TYPE          0
ACTOR1                  0
ASSOC_ACTOR_1       52767
INTER1                  0
ACTOR2              15189
ASSOC_ACTOR_2       54368
INTER2                  0
INTERACTION             0
REGION                  0
COUNTRY                 0
ADMIN1                  0
ADMIN2                  0
ADMIN3              13204
LOCATION                0
LATITUDE                0
LONGITUDE               0
GEO_PRECISION           0
SOURCE                  0
SOURCE_SCALE            0
NOTES                2604
FATALITIES              0
TIMESTAMP               0
dtype: int64

In [7]:
#dropping null values
df.dropna(inplace = True)
df

,ISO,EVENT_ID_CNTY,EVENT_ID_NO_CNTY,EVENT_DATE,YEAR,TIME_PRECISION,EVENT_TYPE,SUB_EVENT_TYPE,ACTOR1,ASSOC_ACTOR_1,...,ADMIN3,LOCATION,LATITUDE,LONGITUDE,GEO_PRECISION,SOURCE,SOURCE_SCALE,NOTES,FATALITIES,TIMESTAMP
12854,24,ANG2923,2923,15-juillet-2009,2009,3,Violence against civilians,Sexual violence,Police Forces of Angola (1975-),Military Forces of Angola (1975-); Civilians (...,...,Maianga,Luanda,-8838,13234,3,IRIN,International,"almost 18,000 people have been deported to the...",0,1571091923
12898,24,ANG2969,2969,28-juillet-2012,2012,1,Riots,Violent demonstration,Rioters (Angola),UNITA: National Union for the Total Independen...,...,Cayavi,Bhisho,-12854,13928,1,Think Africa Press,Other,"A protest becomes violent, at least two people...",2,1552577509
12909,24,ANG2983,2983,15-juin-2013,2013,1,Protests,Protest with intervention,Protesters (Angola),Women (Angola),...,Cuango,Cafunfo,"-8,78","17,99",2,Maka Angola,National,"More than 15,000 citizens took to the streets ...",0,1559160528
13020,24,ANG3096,3096,03-mai-2017,2017,1,Protests,Excessive force against protesters,Protesters (Angola),Prisoners (Angola),...,Maianga,Luanda,-8838,13234,1,VOA,International,At least 20 people were injured when police an...,0,1552576897
13027,24,ANG3105,3105,17-mai-2017,2017,1,Riots,Mob violence,Rioters (Angola),MPLA: Popular Movement for the Liberation of A...,...,Kuito Kuanavale,Cuito Cuanavale,-15167,19183,1,VOA,International,MPLA supporters attacked and stoned the Unita ...,0,1552576893
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65526,404,KEN315,315,25-octobre-1998,1998,1,Violence against civilians,Attack,OLF: Oromo Liberation Front,Borana Ethnic Militia (Kenya),...,Township,Budada,1735,"40,94",2,All Africa,Regional,OLF and Borana ethnic militia attack civilians...,28,1552577673
65527,404,KEN316,316,25-octobre-1998,1998,1,Violence against civilians,Attack,OLF: Oromo Liberation Front,Borana Ethnic Militia (Kenya),...,Township,Gerari,1799,40158,2,All Africa,Regional,OLF and Borana ethnic militia attack civilians...,28,1552577673
65528,404,KEN317,317,25-octobre-1998,1998,1,Violence against civilians,Attack,OLF: Oromo Liberation Front,Borana Ethnic Militia (Kenya),...,Township,Muduma,1579,40259,2,All Africa,Regional,OLF and Borana ethnic militia attack civilians...,28,1552577673
65529,404,KEN313,313,25-octobre-1998,1998,1,Violence against civilians,Attack,Borana Ethnic Militia (Ethiopia),OLF: Oromo Liberation Front,...,Township,Tuli,1643,40343,1,Reuters,International,Ethnic raiders and OLF attack Degodia Somali e...,28,1553544833
65530,404,KEN318,318,25-octobre-1998,1998,1,Violence against civilians,Attack,OLF: Oromo Liberation Front,Borana Ethnic Militia (Kenya),...,Township,Tuli,1643,40343,1,All Africa,Regional,OLF and Borana ethnic militia attack civilians...,28,1553544833

In [8]:
df.describe()

,ISO,EVENT_ID_NO_CNTY,YEAR,TIME_PRECISION,INTER1,INTER2,INTERACTION,GEO_PRECISION,FATALITIES,TIMESTAMP
count,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1627.000000,1.627000e+03
mean,201.303012,8263.755378,2016.119852,1.129072,3.770744,5.311002,38.714813,1.269207,3.460356,1.582706e+09
std,90.378504,10483.372004,5.565424,0.389669,1.498151,2.162898,16.539521,0.493555,19.679133,1.475060e+07
min,24.000000,7.000000,1997.000000,1.000000,1.000000,1.000000,11.000000,1.000000,0.000000,1.552576e+09
25%,140.000000,1648.500000,2015.000000,1.000000,3.000000,4.000000,23.000000,1.000000,0.000000,1.571260e+09
50%,180.000000,3787.000000,2019.000000,1.000000,4.000000,7.000000,37.000000,1.000000,0.000000,1.580773e+09
75%,231.000000,10529.000000,2020.000000,1.000000,5.000000,7.000000,55.000000,1.000000,2.000000,1.594971e+09
max,404.000000,47793.000000,2021.000000,3.000000,8.000000,8.000000,78.000000,3.000000,600.000000,1.610411e+09

In [9]:
df.isnull().sum()

ISO                 0
EVENT_ID_CNTY       0
EVENT_ID_NO_CNTY    0
EVENT_DATE          0
YEAR                0
TIME_PRECISION      0
EVENT_TYPE          0
SUB_EVENT_TYPE      0
ACTOR1              0
ASSOC_ACTOR_1       0
INTER1              0
ACTOR2              0
ASSOC_ACTOR_2       0
INTER2              0
INTERACTION         0
REGION              0
COUNTRY             0
ADMIN1              0
ADMIN2              0
ADMIN3              0
LOCATION            0
LATITUDE            0
LONGITUDE           0
GEO_PRECISION       0
SOURCE              0
SOURCE_SCALE        0
NOTES               0
FATALITIES          0
TIMESTAMP           0
dtype: int64

In [10]:
df.head(5)

,ISO,EVENT_ID_CNTY,EVENT_ID_NO_CNTY,EVENT_DATE,YEAR,TIME_PRECISION,EVENT_TYPE,SUB_EVENT_TYPE,ACTOR1,ASSOC_ACTOR_1,...,ADMIN3,LOCATION,LATITUDE,LONGITUDE,GEO_PRECISION,SOURCE,SOURCE_SCALE,NOTES,FATALITIES,TIMESTAMP
12854,24,ANG2923,2923,15-juillet-2009,2009,3,Violence against civilians,Sexual violence,Police Forces of Angola (1975-),Military Forces of Angola (1975-); Civilians (...,...,Maianga,Luanda,-8838,13234,3,IRIN,International,"almost 18,000 people have been deported to the...",0,1571091923
12898,24,ANG2969,2969,28-juillet-2012,2012,1,Riots,Violent demonstration,Rioters (Angola),UNITA: National Union for the Total Independen...,...,Cayavi,Bhisho,-12854,13928,1,Think Africa Press,Other,"A protest becomes violent, at least two people...",2,1552577509
12909,24,ANG2983,2983,15-juin-2013,2013,1,Protests,Protest with intervention,Protesters (Angola),Women (Angola),...,Cuango,Cafunfo,"-8,78","17,99",2,Maka Angola,National,"More than 15,000 citizens took to the streets ...",0,1559160528
13020,24,ANG3096,3096,03-mai-2017,2017,1,Protests,Excessive force against protesters,Protesters (Angola),Prisoners (Angola),...,Maianga,Luanda,-8838,13234,1,VOA,International,At least 20 people were injured when police an...,0,1552576897
13027,24,ANG3105,3105,17-mai-2017,2017,1,Riots,Mob violence,Rioters (Angola),MPLA: Popular Movement for the Liberation of A...,...,Kuito Kuanavale,Cuito Cuanavale,-15167,19183,1,VOA,International,MPLA supporters attacked and stoned the Unita ...,0,1552576893

In [14]:
df['TIMESTAMP'] = pd.to_datetime(df["TIMESTAMP"])

In [15]:
df['TIMESTAMP']

12854   1970-01-01 00:00:01.571091923
12898   1970-01-01 00:00:01.552577509
12909   1970-01-01 00:00:01.559160528
13020   1970-01-01 00:00:01.552576897
13027   1970-01-01 00:00:01.552576893
                     ...
65526   1970-01-01 00:00:01.552577673
65527   1970-01-01 00:00:01.552577673
65528   1970-01-01 00:00:01.552577673
65529   1970-01-01 00:00:01.553544833
65530   1970-01-01 00:00:01.553544833
Name: TIMESTAMP, Length: 1627, dtype: datetime64[ns]

In [22]:
df['REGION']

12854     Middle Africa
12898     Middle Africa
12909     Middle Africa
13020     Middle Africa
13027     Middle Africa
              ...
65526    Eastern Africa
65527    Eastern Africa
65528    Eastern Africa
65529    Eastern Africa
65530    Eastern Africa
Name: REGION, Length: 1627, dtype: object

In [18]:
import matplotlib.pyplot as plt
import seaborn as sns
x = df['COUNTRY']
y = df['EVENT_TYPE']
plt.hist(x)

TypeError: hist() got multiple values for argument 'bins'